// nuxt/app/pages/[locale]/blog/index.vue
<script setup lang="ts">
import type { Article } from '#shared/types/strapi';

const route = useRoute();
assertLocale(String(route.params.locale));

const locale = useLocale();
const strapi = useStrapiClient();

const { data: articles } = await useAsyncData(
  computed(() => `articles-${locale.value}`),
  () =>
    strapi.collection<Article>('articles', {
      locale: locale.value,
      sort: 'publishedAt:desc',
    }),
  { watch: [locale], default: () => [] }
);

const { data: blogPage } = await useIndexPage('blog-page', locale);
const { data: global } = await useGlobal(locale);

useLaunchpadSeo({
  seo: computed(() => blogPage.value?.seo),
  global,
  locale,
});
</script>

<template>
  <div class="relative overflow-hidden pt-40 pb-20">
    <AmbientColor />
    <Container class="relative z-10">
      <Heading data-reveal>{{ blogPage?.heading ?? 'Blog' }}</Heading>
      <Subheading v-if="blogPage?.sub_heading" class="mt-4" data-reveal>
        {{ blogPage.sub_heading }}
      </Subheading>

      <div
        v-if="articles?.length"
        class="mt-16 grid grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-3"
      >
        <ArticleCard
          v-for="(article, index) in articles"
          :key="article.documentId"
          :article="article"
          :locale="locale"
          :delay="index * 80"
        />
      </div>
      <p v-else class="text-muted mt-16 text-center">No articles yet.</p>
    </Container>
  </div>
</template>

// next/app/[locale]/(marketing)/blog/page.tsx
import { type Metadata } from "next";
import { Container } from "@/components/container";
import { Heading } from "@/components/elements/heading";
import { Subheading } from "@/components/elements/subheading";
import { BlogCard } from "@/components/blog-card";
import { FeatureIconContainer } from "@/components/dynamic-zone/features/feature-icon-container";
import { IconClipboardText } from "@tabler/icons-react";
import { BlogPostRows } from "@/components/blog-post-rows";
import { AmbientColor } from "@/components/decorations/ambient-color";
import fetchContentType from "@/lib/strapi/fetchContentType";
import { Article } from "@/types/types";
import { generateMetadataObject } from '@/lib/shared/metadata';


export async function generateMetadata({
  params,
}: {
  params: { locale: string };
}): Promise<Metadata> {
  const pageData = await fetchContentType('blog-page', `filters[locale]=${params.locale}&populate=seo.metaImage`, true)

  const seo = pageData?.seo;
  const metadata = generateMetadataObject(seo);
  return metadata;
}

export default async function Blog({
  params,
}: {
  params: { locale: string };
}) {
  const blogPage = await fetchContentType('blog-page', `filters[locale]=${params.locale}`, true)
  const articles = await fetchContentType('articles', `filters[locale]=${params.locale}`)

  return (
    <div className="relative overflow-hidden py-20 md:py-0">
      <AmbientColor />
      <Container className="flex flex-col items-center justify-between pb-20">
        <div className="relative z-20 py-10 md:pt-40">
          <FeatureIconContainer className="flex justify-center items-center overflow-hidden">
            <IconClipboardText className="h-6 w-6 text-white" />
          </FeatureIconContainer>
          <Heading as="h1" className="mt-4">
            {blogPage.heading}
          </Heading>
          <Subheading className="max-w-3xl mx-auto">
            {blogPage.sub_heading}
          </Subheading>
        </div>

        {articles.data.slice(0, 1).map((article: Article) => (
          <BlogCard article={article} key={article.title} />
        ))}

        <BlogPostRows articles={articles.data} />
      </Container>
    </div>
  );
}
