// nuxt/app/components/blocks/Hero.vue
<script setup lang="ts">
import type { NavbarLink } from '#shared/types/strapi';

withDefaults(
  defineProps<{
    heading?: string;
    sub_heading?: string;
    CTAs?: Array<NavbarLink & { variant?: string }>;
    locale: string;
  }>(),
  { CTAs: () => [] }
);

const hrefFor = (url: string | undefined, locale: string) =>
  url?.startsWith('http') ? url : `/${locale}${url ?? ''}`;
</script>

<template>
  <div
    class="relative flex min-h-[60vh] flex-col items-center justify-center overflow-hidden pt-40 pb-20"
  >
    <AmbientColor />
    <Sparkles class="absolute inset-0 -z-0 h-full w-full" />

    <Container class="relative z-10 flex flex-col items-center">
      <h1
        data-reveal
        class="text-secondary mx-auto max-w-4xl bg-gradient-to-b from-white to-neutral-400 bg-clip-text text-center text-3xl font-bold tracking-tight text-transparent text-balance md:text-6xl md:leading-tight"
      >
        {{ heading }}
      </h1>

      <p
        v-if="sub_heading"
        data-reveal
        style="--reveal-delay: 100ms"
        class="text-muted mx-auto mt-6 max-w-2xl text-center text-base md:text-lg"
      >
        {{ sub_heading }}
      </p>

      <div
        v-if="CTAs.length"
        data-reveal
        style="--reveal-delay: 200ms"
        class="mt-8 flex flex-wrap items-center justify-center gap-4"
      >
        <Button
          v-for="cta in CTAs"
          :key="cta.URL"
          :href="hrefFor(cta.URL, locale)"
          :target="cta.target"
          :variant="cta.variant ?? 'primary'"
        >
          {{ cta.text }}
        </Button>
      </div>
    </Container>
  </div>
</template>

// next/components/dynamic-zone/hero.tsx
'use client';

import { motion } from 'framer-motion';
import Link from 'next/link';
import React from 'react';

import { Cover } from '../decorations/cover';
import ShootingStars from '../decorations/shooting-star';
import StarBackground from '../decorations/star-background';
import { Button as ElementButton } from '../elements/button';
import { Heading } from '../elements/heading';
import { Subheading } from '../elements/subheading';
import { Image } from '@/types/types';
import { strapiImage } from '@/lib/strapi/strapiImage';

export const Hero = ({
  heading,
  sub_heading,
  CTAs,
  locale,
  background
}: {
  heading: string;
  sub_heading: string;
  CTAs: any[];
  locale: string;
  background: Image;
}) => {
  return (
    <div
      className="h-dvh min-h-[600px] overflow-hidden relative flex flex-col bg-cover bg-center"
      style={background ? { backgroundImage: `url('${strapiImage(background?.url)}')` } : undefined}
    >      <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      transition={{ duration: 0.5, delay: 0.5 }}
    >
        <StarBackground />
        <ShootingStars />
      </motion.div>
      <div className='relative z-20 flex flex-col items-start justify-center w-full h-full px-6 md:px-12 lg:px-24 pt-20 pb-10'>
        <Heading
          as="h1"
          className="text-3xl md:text-4xl lg:text-6xl font-semibold max-w-7xl text-start mt-6 relative z-10 py-6 text-white"
        >
          {heading.split(' ').slice(0, -2).join(' ')}{' '}
          <span className='text-secondary'>
            {heading.split(' ').slice(-2).join(' ')}
          </span>
        </Heading>
        <Subheading className="text-start mt-2 md:mt-6 text-base md:text-xl text-muted  max-w-3xl relative z-10">
          {sub_heading}
        </Subheading>
        <div className="flex flex-wrap gap-4 items-center mt-8 w-full">
          {CTAs &&
            CTAs.map((cta) => (
              <ElementButton
                key={cta?.id}
                as={Link}
                href={`/${locale}${cta.URL}`}
                {...(cta.variant && { variant: cta.variant })}
                className="py-3 px-6 text-primary w-full sm:w-auto flex justify-center bg-white hover:bg-white border-none"
              >
                {cta.text}
              </ElementButton>
            ))}
        </div>
      </div>
    </div>
  );
};
