// next/components/elements/button.tsx
import { LinkProps } from 'next/link';
import React from 'react';
import { cn } from "@/lib/utils"

interface ButtonProps {
  variant?: "simple" | "outline" | "primary" | "muted";
  as?: React.ElementType;
  className?: string;
  children?: React.ReactNode;
  href?: LinkProps['href'];
  onClick?: () => void;
  [key: string]: any;
}

export const Button: React.FC<ButtonProps> = ({
  variant = 'primary',
  as: Tag = 'button',
  className,
  children,
  ...props
}) => {
  const variantClass =
    variant === "simple"
      ? "bg-secondary relative z-10 bg-transparent hover:border-secondary/50 hover:bg-secondary/10  border border-transparent text-white text-sm md:text-sm transition font-medium duration-200  rounded-md px-4 py-2  flex items-center justify-center"
      : variant === "outline"
      ? "bg-white relative z-10 hover:bg-secondary/90 hover:shadow-xl  text-black border border-black hover:text-black text-sm md:text-sm transition font-medium duration-200  rounded-md px-4 py-2  flex items-center justify-center"
      : variant === "primary"
      ? "bg-secondary relative z-10 hover:bg-secondary/90  border border-secondary text-black text-sm md:text-sm transition font-medium duration-200  rounded-md px-4 py-2  flex items-center justify-center shadow-[0px_-1px_0px_0px_#FFFFFF60_inset,_0px_1px_0px_0px_#FFFFFF60_inset  hover:-translate-y-1 active:-translate-y-0"
      : variant === "muted"
      ? "bg-neutral-800 relative z-10 hover:bg-neutral-900  border border-transparent text-white text-sm md:text-sm transition font-medium duration-200  rounded-md px-4 py-2  flex items-center justify-center shadow-[0px_1px_0px_0px_#FFFFFF20_inset]"
      : "";
  const Element = Tag as any;
  
  return (
    <Element
      className={cn(
        'bg-secondary relative z-10 bg-transparent hover:border-secondary hover:bg-secondary/50  border border-transparent text-white text-sm md:text-sm transition font-medium duration-200  rounded-md px-4 py-2  flex items-center justify-center ',
        variantClass,
        className
      )}
      {...props}
    >
      {children ?? `Get Started`}
    </Element>
  );
};

// nuxt/app/components/Button.vue
<script setup lang="ts">
import { stripStegaMarkers } from '#shared/lib/stega';
/**
 * Renders an `<a>` when given an href and a `<button>` otherwise.
 *
 * Internal links go through `<NuxtLink>` so navigation stays client-side;
 * external ones fall back to a plain anchor, since there is nothing for the
 * router to do with them.
 */
type Variant = 'primary' | 'secondary' | 'simple' | 'muted';

const props = withDefaults(
  defineProps<{
    href?: string;
    variant?: Variant | string;
    target?: string | null;
  }>(),
  { variant: 'primary' }
);

const base =
  'relative z-10 inline-flex cursor-pointer items-center justify-center rounded-md px-4 py-2 text-sm font-medium transition duration-200 hover:-translate-y-0.5';

const VARIANTS: Record<Variant, string> = {
  primary:
    'bg-secondary text-black shadow-[0px_-1px_0px_0px_#FFFFFF40_inset,0px_1px_0px_0px_#FFFFFF40_inset] hover:bg-white',
  secondary: 'bg-transparent text-white shadow-none',
  simple:
    'bg-transparent text-white shadow-none hover:bg-neutral-800 hover:shadow-[0px_1px_0px_0px_var(--color-neutral-600)_inset]',
  muted:
    'bg-neutral-800 text-white shadow-[0px_1px_0px_0px_var(--color-neutral-600)_inset] hover:bg-neutral-700',
};

const classes = computed(() => [
  base,
  VARIANTS[stripStegaMarkers(props.variant ?? '') as Variant] ?? VARIANTS.primary,
]);

const isExternal = computed(() => !!props.href?.startsWith('http'));
const rel = computed(() =>
  props.target === '_blank' ? 'noopener noreferrer' : undefined
);
</script>

<template>
  <NuxtLink
    v-if="href && !isExternal"
    :to="href"
    :target="target ?? undefined"
    :rel="rel"
    :class="classes"
  >
    <slot />
  </NuxtLink>

  <a
    v-else-if="href"
    :href="href"
    :target="target ?? undefined"
    :rel="rel ?? 'noopener noreferrer'"
    :class="classes"
  >
    <slot />
  </a>

  <button v-else type="button" :class="classes">
    <slot />
  </button>
</template>
