// tanstack/src/components/draft-mode-banner.tsx
import { useRouter } from '@tanstack/react-router';
import { useEffect, useState } from 'react';

/**
 * Draft mode exit banner.
 *
 * Slice 1 ports the UI only — the `/api/exit-preview` endpoint that clears
 * the `draft` cookie will be wired up in slice 6 (preview/draft mode).
 * Until then this component is not mounted anywhere (see $locale.tsx).
 */
export function DraftModeBanner() {
  const router = useRouter();
  const [isExiting, setIsExiting] = useState(false);
  const [isIframe, setIsIframe] = useState(true);

  useEffect(() => {
    setIsIframe(window !== window.top);
  }, []);

  const handleExitDraft = async () => {
    setIsExiting(true);
    try {
      await fetch('/api/exit-preview');
      router.invalidate();
    } catch (error) {
      console.error('Failed to exit draft mode:', error);
      setIsExiting(false);
    }
  };

  if (isIframe) {
    return null;
  }

  return (
    <div className="fixed bottom-4 right-4 z-50 bg-secondary text-black px-6 py-3 rounded-lg shadow-lg flex items-center gap-4">
      <div className="flex items-center gap-2">
        <span className="inline-block w-4 h-4 bg-black rounded-full animate-pulse" />
        <span className="font-semibold">Draft Mode</span>
      </div>
      <button
        onClick={handleExitDraft}
        disabled={isExiting}
        className="bg-black text-white px-4 py-1 rounded text-sm font-medium hover:bg-gray-800 disabled:opacity-50 transition-colors"
      >
        {isExiting ? 'Exiting...' : 'Exit Draft'}
      </button>
    </div>
  );
}

// nuxt/app/components/DraftModeBanner.vue
<script setup lang="ts">
/*
 * Shown only when draft mode is on, and hidden inside the Strapi preview
 * iframe — the admin already provides its own controls there and a second
 * banner would just cover content.
 *
 * The iframe test has to wait for mount: `window.top` does not exist while the
 * page is being rendered on the server.
 */
const isTopLevel = ref(false);

onMounted(() => {
  isTopLevel.value = window.top === window.self;
});
</script>

<template>
  <div
    v-if="isTopLevel"
    class="bg-secondary fixed right-4 bottom-4 z-50 flex items-center gap-4 rounded-lg px-6 py-3 text-black shadow-lg"
  >
    <span class="flex items-center gap-2 font-semibold">
      <span class="inline-block h-4 w-4 animate-pulse rounded-full bg-black" />
      Draft Mode
    </span>
    <a
      href="/api/exit-preview"
      class="rounded bg-black px-4 py-1 text-sm font-medium text-white transition-colors hover:bg-gray-800"
    >
      Exit Draft
    </a>
  </div>
</template>
