// tanstack/src/components/ui/strapi-media.tsx
import React from 'react';

import { getStrapiSource } from '@/lib/strapi/source-map';
import { API_URL, stripStegaMarkers } from '@/lib/utils';

interface StrapiMediaProps
  extends Omit<React.ImgHTMLAttributes<HTMLImageElement>, 'src' | 'alt'> {
  src: string;
  alt?: string | null;
  mime?: string | null;
  width?: number | string;
  height?: number | string;
  videoProps?: Omit<
    React.VideoHTMLAttributes<HTMLVideoElement>,
    'src' | 'className'
  >;
  audioProps?: Omit<
    React.AudioHTMLAttributes<HTMLAudioElement>,
    'src' | 'className'
  >;
}

export function getStrapiMedia(url: string | null): string | null {
  if (url == null) return null;
  const cleanUrl = stripStegaMarkers(url);
  if (cleanUrl.startsWith('data:')) return cleanUrl;
  if (cleanUrl.startsWith('http') || cleanUrl.startsWith('//')) return cleanUrl;

  return API_URL + cleanUrl;
}

/**
 * Renders a Strapi media field. Branches on `mime` so video/audio assets get
 * the right element instead of being fed to <img> (which can't render them).
 * Falls back to <img> when mime is absent or image-like.
 *
 * The `article.image` and `product.images` fields both accept videos (and
 * `article.image` accepts audio too), so a media field is not safe to assume
 * is an image — pass `mime` wherever the media object is in scope.
 *
 * Port of the Next launchpad's `components/ui/strapi-media.tsx`.
 */
export function StrapiMedia({
  src,
  mime,
  alt,
  className,
  videoProps,
  audioProps,
  ...imageProps
}: Readonly<StrapiMediaProps>) {
  // Decode the visual-editing source from the raw URL *before* getStrapiMedia
  // strips the markers, and render it as a literal data attribute the preview
  // overlay reads directly. Undefined outside draft mode -> attribute omitted.
  const strapiSource = getStrapiSource(src);

  if (mime?.startsWith('video/')) {
    const url = getStrapiMedia(src);
    if (!url) return null;
    return (
      <video
        src={url}
        controls
        preload="metadata"
        className={className}
        data-strapi-source={strapiSource}
        {...videoProps}
      />
    );
  }

  if (mime?.startsWith('audio/')) {
    const url = getStrapiMedia(src);
    if (!url) return null;
    return (
      <audio
        src={url}
        controls
        className={className}
        data-strapi-source={strapiSource}
        {...audioProps}
      />
    );
  }

  const imageUrl = getStrapiMedia(src);
  if (!imageUrl) return null;
  return (
    <img
      src={imageUrl}
      alt={alt ?? 'No alternative text provided'}
      className={className}
      data-strapi-source={strapiSource}
      {...imageProps}
    />
  );
}

// nuxt/app/components/StrapiMedia.vue
<script setup lang="ts">
import { isAudio, isVideo, strapiMedia } from '#shared/lib/media';
import { getStrapiSource } from '#shared/lib/source-map';
import type { StrapiMedia as StrapiMediaType } from '#shared/types/strapi';

/**
 * Renders a Strapi media field.
 *
 * Branches on `mime` because LaunchPad's media fields accept videos and audio,
 * not just images — `product.images` and `article.image` both do. Feeding a
 * video to an `<img>` renders a broken icon, so the type has to be respected.
 *
 * Deliberately a plain `<img>` rather than `<NuxtImg>`: these are remote CMS
 * URLs whose dimensions vary per entry, and optimising them would mean either
 * proxying every asset at build time or configuring a remote image service.
 * Neither is worth it for a demo, and both would break draft mode, where the
 * URL is only known per request.
 */
const props = withDefaults(
  defineProps<{
    media?: StrapiMediaType | null;
    /** Overrides `media.alternativeText`; required when the media has none. */
    alt?: string | null;
    width?: number | string;
    height?: number | string;
    loading?: 'lazy' | 'eager';
    /**
     * Visual-editing mapping. Decoded from the media URL automatically — only
     * pass this to override it.
     */
    dataStrapiSource?: string;
  }>(),
  { loading: 'lazy' }
);

const strapiUrl = useStrapiUrl();

const src = computed(() => strapiMedia(props.media?.url, strapiUrl));
const label = computed(() => props.alt ?? props.media?.alternativeText ?? '');

/*
 * Decode from the RAW url, before strapiMedia() strips the markers out of it.
 * Undefined outside draft mode, so the attribute is simply absent in
 * production rather than empty.
 */
const strapiSource = computed(
  () => props.dataStrapiSource ?? getStrapiSource(props.media?.url)
);
</script>

<template>
  <video
    v-if="src && isVideo(media?.mime)"
    :src="src"
    controls
    preload="metadata"
    :data-strapi-source="strapiSource"
  />

  <audio
    v-else-if="src && isAudio(media?.mime)"
    :src="src"
    controls
    :data-strapi-source="strapiSource"
  />

  <img
    v-else-if="src"
    :src="src"
    :alt="label"
    :width="width"
    :height="height"
    :loading="loading"
    decoding="async"
    :data-strapi-source="strapiSource"
  />
</template>
