// nuxt/app/components/blocks/Hero.vue
<script setup lang="ts">
import type { NavbarLink } from '#shared/types/strapi';

withDefaults(
  defineProps<{
    heading?: string;
    sub_heading?: string;
    CTAs?: Array<NavbarLink & { variant?: string }>;
    locale: string;
  }>(),
  { CTAs: () => [] }
);

const hrefFor = (url: string | undefined, locale: string) =>
  url?.startsWith('http') ? url : `/${locale}${url ?? ''}`;
</script>

<template>
  <div
    class="relative flex min-h-[60vh] flex-col items-center justify-center overflow-hidden pt-40 pb-20"
  >
    <AmbientColor />
    <Sparkles class="absolute inset-0 -z-0 h-full w-full" />

    <Container class="relative z-10 flex flex-col items-center">
      <h1
        data-reveal
        class="text-secondary mx-auto max-w-4xl bg-gradient-to-b from-white to-neutral-400 bg-clip-text text-center text-3xl font-bold tracking-tight text-transparent text-balance md:text-6xl md:leading-tight"
      >
        {{ heading }}
      </h1>

      <p
        v-if="sub_heading"
        data-reveal
        style="--reveal-delay: 100ms"
        class="text-muted mx-auto mt-6 max-w-2xl text-center text-base md:text-lg"
      >
        {{ sub_heading }}
      </p>

      <div
        v-if="CTAs.length"
        data-reveal
        style="--reveal-delay: 200ms"
        class="mt-8 flex flex-wrap items-center justify-center gap-4"
      >
        <Button
          v-for="cta in CTAs"
          :key="cta.URL"
          :href="hrefFor(cta.URL, locale)"
          :target="cta.target"
          :variant="cta.variant ?? 'primary'"
        >
          {{ cta.text }}
        </Button>
      </div>
    </Container>
  </div>
</template>

// tanstack/src/components/dynamic-zone/hero.tsx
import { Link } from '@tanstack/react-router';
import { motion } from 'framer-motion';

import ShootingStars from '../decorations/shooting-star';
import StarBackground from '../decorations/star-background';
import { Button } from '../elements/button';
import { Heading } from '../elements/heading';
import { Subheading } from '../elements/subheading';
import { ClientOnly } from '@/components/client-only';

export const Hero = ({
  heading,
  sub_heading,
  CTAs,
  locale,
}: {
  heading: string;
  sub_heading: string;
  CTAs: Array<any>;
  locale: string;
}) => {
  return (
    <div className="h-screen overflow-hidden relative flex flex-col items-center justify-center">
      <ClientOnly>
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.5, delay: 0.5 }}
        >
          <StarBackground />
          <ShootingStars />
        </motion.div>
      </ClientOnly>
      <Heading
        as="h1"
        className="text-4xl md:text-4xl lg:text-8xl font-semibold max-w-7xl mx-auto text-center mt-6 relative z-10  py-6"
      >
        {heading}
      </Heading>
      <Subheading className="text-center mt-2 md:mt-6 text-base md:text-xl text-muted  max-w-3xl mx-auto relative z-10">
        {sub_heading}
      </Subheading>
      <div className="flex space-x-2 items-center mt-8">
        {CTAs &&
          CTAs.map((cta) => (
            <Button
              key={cta?.id}
              as={Link}
              to={`/${locale}${cta.URL}`}
              {...(cta.variant ? { variant: cta.variant } : {})}
            >
              {cta.text}
            </Button>
          ))}
      </div>
      <div className="absolute inset-x-0 bottom-0 h-80 w-full bg-gradient-to-t from-charcoal to-transparent" />
    </div>
  );
};
