// nuxt/app/components/LocaleSwitcher.vue
<script setup lang="ts">
import { LOCALES } from '#shared/lib/i18n';

/**
 * Locale toggle.
 *
 * Rendered as real links so it works without JavaScript and search engines can
 * follow it — the React version used a click handler and a router call.
 *
 * Three cases, and the third is the one that is easy to get wrong:
 *
 *  - No `localizedPaths` (a static route like `/en/blog`): swap the locale
 *    segment. The path is the same in every locale.
 *  - A translation exists: link to its slug, which differs — `/en/blog/foo`
 *    is `/fr/blog/quelque-chose`.
 *  - `localizedPaths` is present but has no entry for that locale: the entry is
 *    genuinely untranslated. LaunchPad's demo data has exactly one of these, a
 *    French-only article. Swapping the segment there produces a URL that does
 *    not exist, so the locale is rendered disabled instead of as a dead link.
 */
const props = defineProps<{
  currentLocale: string;
  /**
   * Map of locale -> path *after* the locale prefix, e.g. `blog/bonjour`.
   * Resolved by the layout — see `useLocalizedPaths`.
   */
  localizedPaths?: Record<string, string>;
}>();

const route = useRoute();

/** True when this page is a localised entry that has no such translation. */
function isMissing(locale: string): boolean {
  return !!props.localizedPaths && props.localizedPaths[locale] === undefined;
}

function hrefFor(locale: string): string {
  const localized = props.localizedPaths?.[locale];
  if (localized !== undefined) {
    return localized === '' ? `/${locale}` : `/${locale}/${localized}`;
  }
  const rest = route.path.split('/').filter(Boolean).slice(1);
  return rest.length ? `/${locale}/${rest.join('/')}` : `/${locale}`;
}

const baseClass =
  'flex w-8 items-center justify-center rounded-md py-1 text-sm leading-[110%] transition duration-200';
const activeClass =
  'bg-neutral-800 text-white shadow-[0px_1px_0px_0px_var(--color-neutral-600)_inset]';
const linkClass =
  'cursor-pointer text-white hover:bg-neutral-800 hover:text-white/80 hover:shadow-[0px_1px_0px_0px_var(--color-neutral-600)_inset]';
</script>

<template>
  <div class="flex gap-2 rounded-md p-1">
    <template v-for="locale in LOCALES" :key="locale">
      <span
        v-if="isMissing(locale)"
        :class="[baseClass, 'cursor-not-allowed text-neutral-600']"
        aria-disabled="true"
        title="Not available in this language"
      >
        {{ locale }}
      </span>
      <NuxtLink
        v-else
        :to="hrefFor(locale)"
        :hreflang="locale"
        :aria-current="locale === currentLocale ? 'true' : undefined"
        :class="[baseClass, linkClass, locale === currentLocale && activeClass]"
      >
        {{ locale }}
      </NuxtLink>
    </template>
  </div>
</template>

// tanstack/src/components/locale-switcher.tsx
import { useMatches, useRouter } from '@tanstack/react-router';

import { i18n } from '@/i18n.config';
import { cn } from '@/lib/utils';

/**
 * Reads `localizedSlugs` from the deepest matched route's loaderData.
 *
 * Each page route (`$locale/index`, `$locale/$slug`, etc.) returns
 * `{ localizedSlugs: Record<locale, slug> }` from its loader. This walks
 * matches deepest-first and returns the first one that exposes the map,
 * mirroring Next's `SlugContext` pattern without the React context.
 */
function useLocalizedSlugs(): Record<string, string> | null {
  const matches = useMatches();
  for (let i = matches.length - 1; i >= 0; i--) {
    const data = matches[i].loaderData as
      | { localizedSlugs?: Record<string, string> }
      | undefined;
    if (data && data.localizedSlugs) {
      return data.localizedSlugs;
    }
  }
  return null;
}

/**
 * Locale toggle. When the current route exposes `localizedSlugs`, navigates
 * to the localized slug for the target locale. Otherwise falls back to just
 * swapping the locale segment in the current pathname.
 */
export function LocaleSwitcher({ currentLocale }: { currentLocale: string }) {
  const router = useRouter();
  const localizedSlugs = useLocalizedSlugs();

  const buildTargetPath = (targetLocale: string): string => {
    if (localizedSlugs) {
      const slug = localizedSlugs[targetLocale];
      if (slug === undefined) {
        // No localization for this route → send to the target locale's home.
        return `/${targetLocale}`;
      }
      return slug === '' ? `/${targetLocale}` : `/${targetLocale}/${slug}`;
    }

    // Fallback: swap the locale segment in the current pathname.
    const segments = router.state.location.pathname.split('/');
    if (segments.length < 2) return `/${targetLocale}`;
    segments[1] = targetLocale;
    return segments.join('/') || `/${targetLocale}`;
  };

  const handleClick = (targetLocale: string) => {
    router.navigate({ to: buildTargetPath(targetLocale) as any });
  };

  return (
    <div className="flex gap-2 p-1 rounded-md">
      {i18n.locales.map((locale) => (
        <button
          type="button"
          key={locale}
          onClick={() => handleClick(locale)}
          className={cn(
            'flex cursor-pointer items-center justify-center text-sm leading-[110%] w-8 py-1 rounded-md hover:bg-neutral-800 hover:text-white/80 text-white hover:shadow-[0px_1px_0px_0px_var(--neutral-600)_inset] transition duration-200',
            locale === currentLocale
              ? 'bg-neutral-800 text-white shadow-[0px_1px_0px_0px_var(--neutral-600)_inset]'
              : ''
          )}
        >
          {locale}
        </button>
      ))}
    </div>
  );
}
