// next/components/dynamic-zone/cta.tsx
'use client';

import { motion } from 'framer-motion';
import Link from 'next/link';
import React from 'react';

import { Container } from '../container';
import { AmbientColor } from '../decorations/ambient-color';
import { Button } from '../elements/button';

export const CTA = ({
  heading,
  sub_heading,
  CTAs,
  locale,
}: {
  heading: string;
  sub_heading: string;
  CTAs: any[];
  locale: string;
}) => {
  return (
    <div className="relative py-40">
      <AmbientColor />
      <Container className="flex flex-col md:flex-row justify-between items-center w-full px-8">
        <div className="flex flex-col">
          <motion.h2 className="text-white text-xl text-center md:text-left md:text-3xl font-bold mx-auto md:mx-0 max-w-xl ">
            {heading}
          </motion.h2>
          <p className="max-w-md mt-8 text-center md:text-left text-sm md:text-base mx-auto md:mx-0 text-neutral-400">
            {sub_heading}
          </p>
        </div>
        <div className="flex items-center gap-4">
          {CTAs &&
            CTAs.map((cta, index) => (
              <Button
                as={Link}
                key={index}
                href={`/${locale}${cta.URL}`}
                variant={cta.variant}
                className="py-3"
              >
                {cta.text}
              </Button>
            ))}
        </div>
      </Container>
    </div>
  );
};

// nuxt/app/components/blocks/Cta.vue
<script setup lang="ts">
import type { NavbarLink } from '#shared/types/strapi';

withDefaults(
  defineProps<{
    heading?: string;
    sub_heading?: string;
    CTAs?: Array<NavbarLink & { variant?: string }>;
    locale: string;
  }>(),
  { CTAs: () => [] }
);

const hrefFor = (url: string | undefined, locale: string) =>
  url?.startsWith('http') ? url : `/${locale}${url ?? ''}`;
</script>

<template>
  <div class="relative overflow-hidden py-40">
    <AmbientColor />
    <Container class="relative z-10 flex flex-col items-center">
      <Heading data-reveal>{{ heading }}</Heading>
      <Subheading v-if="sub_heading" class="mt-4" data-reveal>
        {{ sub_heading }}
      </Subheading>
      <div
        v-if="CTAs.length"
        class="mt-8 flex flex-wrap items-center justify-center gap-4"
        data-reveal
      >
        <Button
          v-for="cta in CTAs"
          :key="cta.URL"
          :href="hrefFor(cta.URL, locale)"
          :target="cta.target"
          :variant="cta.variant ?? 'primary'"
        >
          {{ cta.text }}
        </Button>
      </div>
    </Container>
  </div>
</template>
