// next/components/pricing/index.tsx
"use client";

import React from "react";
import { Container } from "../container";
import { FeatureIconContainer } from "../features/feature-icon-container";
import { Heading } from "../elements/heading";
import { Subheading } from "../elements/subheading";
import { IconCheck, IconPlus, IconReceipt2 } from "@tabler/icons-react";
import { cn } from "@/lib/utils";
import { Button } from "../elements/button";
import getPlans, { Plan } from "./plans";
import { useLocale } from "next-intl";
import { Locale } from "@/config";

export const Pricing = () => {
  const locale = useLocale();
  const plans = getPlans(locale as Locale);
  const onClick = (plan: Plan) => {
    console.log("click", plan);
  };
  return (
    <div>
      <Container>
        <FeatureIconContainer className="flex justify-center items-center overflow-hidden">
          <IconReceipt2 className="h-6 w-6 text-white" />
        </FeatureIconContainer>
        <Heading className="pt-4">Pricing</Heading>
        <Subheading className="max-w-3xl mx-auto">
          Choose your payload.
        </Subheading>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 max-w-7xl mx-auto gap-4 py-20 lg:items-start">
          {plans.map((plan, idx) => (
            <Card onClick={() => onClick(plan)} key={plan.title} plan={plan} />
          ))}
        </div>
      </Container>
    </div>
  );
};

const Card = ({ plan, onClick }: { plan: Plan; onClick: () => void }) => {
  return (
    <div
      className={cn(
        "p-4 md:p-4 rounded-3xl bg-neutral-900 border-2 border-neutral-800",
        plan.featured && "border-neutral-50 bg-neutral-100"
      )}
    >
      <div
        className={cn(
          "p-4 bg-neutral-800 rounded-2xl shadow-[0px_-1px_0px_0px_var(--neutral-700)]",
          plan.featured && "bg-white shadow-aceternity"
        )}
      >
        <div className="flex justify-between items-center">
          <p className={cn("font-medium", plan.featured && "text-black")}>
            {plan.title}
          </p>
          {plan.featured && (
            <div
              className={cn(
                "font-medium text-xs px-3 py-1 rounded-full relative bg-neutral-900"
              )}
            >
              <div className="absolute inset-x-0 bottom-0 w-3/4 mx-auto h-px bg-gradient-to-r from-transparent via-indigo-500 to-transparent"></div>
              Featured
            </div>
          )}
        </div>
        <div className="mt-8">
          {!plan.exception && (
            <span
              className={cn(
                "text-lg font-bold text-neutral-500",
                plan.featured && "text-neutral-700"
              )}
            >
              $
            </span>
          )}
          <span
            className={cn("text-4xl font-bold", plan.featured && "text-black")}
          >
            {plan.price}
          </span>
          {!plan.exception && (
            <span
              className={cn(
                "text-lg font-normal text-neutral-500 ml-2",
                plan.featured && "text-neutral-700"
              )}
            >
              / {plan.subtitle}
            </span>
          )}
        </div>
        <Button
          variant="outline"
          className={cn(
            "w-full mt-10 mb-4",
            plan.featured &&
              "bg-black text-white hover:bg-black/80 hover:text-white"
          )}
          onClick={onClick}
        >
          {plan.ctaText}
        </Button>
      </div>
      <div className="mt-1 p-4">
        {plan.features.map((feature, idx) => (
          <Step featured={plan.featured} key={idx}>
            {feature.content}
          </Step>
        ))}
      </div>
      {plan.additionalFeatures && plan.additionalFeatures.length > 0 && (
        <Divider featured={plan.featured} />
      )}
      <div className="p-4">
        {plan.additionalFeatures?.map((feature, idx) => (
          <Step featured={plan.featured} additional key={idx}>
            {feature.content}
          </Step>
        ))}
      </div>
    </div>
  );
};

const Step = ({
  children,
  additional,
  featured,
}: {
  children: React.ReactNode;
  additional?: boolean;
  featured?: boolean;
}) => {
  return (
    <div className="flex items-start justify-start gap-2 my-4">
      <div
        className={cn(
          "h-4 w-4 rounded-full bg-neutral-700 flex items-center justify-center flex-shrink-0 mt-0.5",
          additional ? "bg-indigo-600" : "bg-neutral-700"
        )}
      >
        <IconCheck className="h-3 w-3 [stroke-width:4px] text-neutral-300" />
      </div>
      <div
        className={cn(
          "font-medium text-white text-sm",
          featured && "text-black"
        )}
      >
        {children}
      </div>
    </div>
  );
};

const Divider = ({ featured }: { featured?: boolean }) => {
  return (
    <div className="relative">
      <div
        className={cn("w-full h-px bg-neutral-950", featured && "bg-white")}
      />
      <div
        className={cn(
          "w-full h-px bg-neutral-800",
          featured && "bg-neutral-200"
        )}
      />
      <div
        className={cn(
          "absolute inset-0 h-5 w-5 m-auto rounded-xl bg-neutral-800 shadow-[0px_-1px_0px_0px_var(--neutral-700)] flex items-center justify-center",
          featured && "bg-white shadow-aceternity"
        )}
      >
        <IconPlus
          className={cn(
            "h-3 w-3 [stroke-width:4px] text-neutral-300",
            featured && "text-black"
          )}
        />
      </div>
    </div>
  );
};

// nuxt/app/components/blocks/Pricing.vue
<script setup lang="ts">
import { formatPrice } from '#shared/lib/i18n';
import type { NavbarLink, Perk } from '#shared/types/strapi';

interface Plan {
  name: string;
  price?: number | null;
  sub_text?: string | null;
  featured?: boolean;
  CTA?: (NavbarLink & { variant?: string }) | null;
  perks?: Perk[];
  additional_perks?: Perk[];
}

const props = withDefaults(
  defineProps<{
    heading?: string;
    sub_heading?: string;
    plans?: Plan[];
    locale: string;
  }>(),
  { plans: () => [] }
);

const price = (value?: number | null) => formatPrice(value, props.locale);

const ctaHref = (cta: Plan['CTA']) =>
  cta?.URL?.startsWith('http') ? cta.URL : `/${props.locale}${cta?.URL ?? ''}`;
</script>

<template>
  <div class="relative py-20">
    <Container>
      <Heading data-reveal>{{ heading }}</Heading>
      <Subheading v-if="sub_heading" class="mt-4" data-reveal>
        {{ sub_heading }}
      </Subheading>

      <div
        v-if="plans.length"
        class="mx-auto mt-16 grid max-w-7xl grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-4 lg:items-start"
      >
        <div
          v-for="(plan, index) in plans"
          :key="plan.name"
          data-reveal
          :style="`--reveal-delay: ${index * 80}ms`"
          class="rounded-3xl border-2 p-4"
          :class="
            plan.featured
              ? 'border-cyan-600 bg-neutral-900'
              : 'border-neutral-800 bg-neutral-900'
          "
        >
          <div class="rounded-2xl bg-neutral-800 p-4">
            <p class="text-sm font-medium text-neutral-200">{{ plan.name }}</p>
            <p
              v-if="price(plan.price)"
              class="mt-8 text-4xl font-bold text-white"
            >
              {{ price(plan.price) }}
            </p>
            <p v-if="plan.sub_text" class="text-muted mt-1 text-xs">
              {{ plan.sub_text }}
            </p>
            <Button
              v-if="plan.CTA"
              class="mt-8 mb-2 w-full"
              :variant="plan.featured ? 'primary' : 'muted'"
              :href="ctaHref(plan.CTA)"
            >
              {{ plan.CTA.text }}
            </Button>
          </div>

          <ul class="mt-1 space-y-4 p-4">
            <li
              v-for="(perk, i) in plan.perks ?? []"
              :key="`perk-${i}`"
              class="flex items-start gap-2"
            >
              <svg
                class="mt-0.5 h-4 w-4 shrink-0 text-cyan-400"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="3"
                stroke-linecap="round"
                stroke-linejoin="round"
                aria-hidden="true"
              >
                <path d="M5 12l5 5L20 7" />
              </svg>
              <span class="text-muted text-sm">{{ perk.text }}</span>
            </li>
            <li
              v-for="(perk, i) in plan.additional_perks ?? []"
              :key="`extra-${i}`"
              class="flex items-start gap-2 opacity-70"
            >
              <svg
                class="mt-0.5 h-4 w-4 shrink-0 text-neutral-500"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="3"
                stroke-linecap="round"
                stroke-linejoin="round"
                aria-hidden="true"
              >
                <path d="M5 12l5 5L20 7" />
              </svg>
              <span class="text-muted text-sm">{{ perk.text }}</span>
            </li>
          </ul>
        </div>
      </div>
    </Container>
  </div>
</template>
