// next/components/dynamic-zone/related-articles.tsx
'use client';

import React from 'react';

import { BlogCardVertical } from '../blog-card';

export const RelatedArticles = ({
  heading,
  sub_heading,
  articles,
  locale,
}: {
  heading: string;
  sub_heading: string;
  articles: any[];
  locale: string;
}) => {
  return (
    <div className="mt-12 pb-20">
      <h2 className="text-2xl font-bold text-neutral-200 mb-10">{heading}</h2>
      <div className="grid grid-cols-1 md:grid-cols-3 gap-10">
        {articles.map((article) => (
          <BlogCardVertical
            key={article.title}
            article={article}
            locale={locale}
          />
        ))}
      </div>
    </div>
  );
};

// nuxt/app/components/blocks/RelatedArticles.vue
<script setup lang="ts">
import type { Article } from '#shared/types/strapi';

withDefaults(
  defineProps<{
    heading?: string;
    sub_heading?: string;
    articles?: Article[];
    locale: string;
  }>(),
  { articles: () => [] }
);
</script>

<template>
  <div class="relative py-20">
    <Container>
      <Heading data-reveal>{{ heading }}</Heading>
      <Subheading v-if="sub_heading" class="mt-4" data-reveal>
        {{ sub_heading }}
      </Subheading>
      <div
        v-if="articles.length"
        class="mt-16 grid grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-3"
      >
        <ArticleCard
          v-for="(article, index) in articles"
          :key="article.documentId ?? index"
          :article="article"
          :locale="locale"
          :delay="index * 80"
        />
      </div>
    </Container>
  </div>
</template>
